# Generated by Django 3.1.7 on 2021-03-30 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(max_length=50)),
                ('is_end', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('authors', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('publishing_house', models.CharField(max_length=100)),
                ('year_of_publishing', models.IntegerField()),
                ('number_of_pages', models.IntegerField()),
                ('number_of_copies', models.IntegerField()),
                ('udc', models.CharField(max_length=50)),
                ('bbk', models.CharField(max_length=50)),
                ('keywords', models.CharField(max_length=50)),
                ('short_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClearanceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=10)),
                ('residence_address', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=12)),
                ('is_end', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=12)),
                ('residence_address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=500)),
                ('publishing_house', models.CharField(max_length=100)),
                ('the_year_of_publishing', models.IntegerField()),
                ('number_of_pages', models.IntegerField()),
                ('number_of_copies', models.IntegerField()),
                ('application_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.applicationstatus')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.clients')),
            ],
        ),
        migrations.CreateModel(
            name='Formalization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('books', models.ManyToManyField(to='todolist.Books')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.clients')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.employee')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.clearancestatus')),
            ],
        ),
    ]
