# Generated by Django 3.1.7 on 2021-04-02 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationstatus',
            name='is_end',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='is_end',
        ),
        migrations.AddField(
            model_name='request',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='residence_address',
            field=models.CharField(max_length=50, verbose_name='Адрес'),
        ),
        migrations.RemoveField(
            model_name='formalization',
            name='books',
        ),
        migrations.AddField(
            model_name='formalization',
            name='books',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='todolist.books'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formalization',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='todolist.clients'),
        ),
        migrations.AlterField(
            model_name='formalization',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='todolist.employee'),
        ),
        migrations.AlterField(
            model_name='formalization',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='todolist.clearancestatus'),
        ),
        migrations.AlterField(
            model_name='request',
            name='application_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='todolist.applicationstatus'),
        ),
        migrations.AlterField(
            model_name='request',
            name='authors',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='todolist.clients'),
        ),
    ]
