# Generated by Django 3.1.7 on 2021-04-02 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20210402_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formalization',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='todolist.clearancestatus', verbose_name='Статус'),
        ),
    ]
