# Generated by Django 3.1.7 on 2021-04-02 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20210403_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearancestatus',
            name='status_name',
            field=models.CharField(max_length=50, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='telephone',
            field=models.CharField(max_length=12, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='formalization',
            name='books',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='todolist.books', verbose_name='Название книги'),
        ),
        migrations.AlterField(
            model_name='formalization',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='todolist.clients', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='formalization',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='todolist.employee', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='formalization',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
