# Generated by Django 3.1.7 on 2021-04-02 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20210403_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatus',
            name='application_status',
            field=models.CharField(max_length=50, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='books',
            name='authors',
            field=models.CharField(max_length=100, verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='books',
            name='bbk',
            field=models.CharField(max_length=50, verbose_name='ББК'),
        ),
        migrations.AlterField(
            model_name='books',
            name='cost',
            field=models.FloatField(verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='books',
            name='keywords',
            field=models.CharField(max_length=50, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='books',
            name='number_of_copies',
            field=models.IntegerField(verbose_name='Количество экзмепляров'),
        ),
        migrations.AlterField(
            model_name='books',
            name='number_of_pages',
            field=models.IntegerField(verbose_name='Количество страниц'),
        ),
        migrations.AlterField(
            model_name='books',
            name='publishing_house',
            field=models.CharField(max_length=100, verbose_name='Издательство'),
        ),
        migrations.AlterField(
            model_name='books',
            name='short_description',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='books',
            name='udc',
            field=models.CharField(max_length=50, verbose_name='УДК'),
        ),
        migrations.AlterField(
            model_name='books',
            name='year_of_publishing',
            field=models.IntegerField(verbose_name='Год издания'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='residence_address',
            field=models.CharField(max_length=50, verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='telephone',
            field=models.CharField(max_length=12, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='request',
            name='application_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='todolist.applicationstatus', verbose_name='Состояние заявки'),
        ),
        migrations.AlterField(
            model_name='request',
            name='authors',
            field=models.CharField(max_length=50, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='request',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='todolist.clients', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='request',
            name='keywords',
            field=models.CharField(max_length=500, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название книги'),
        ),
        migrations.AlterField(
            model_name='request',
            name='number_of_copies',
            field=models.IntegerField(verbose_name='Количество экзмепляров'),
        ),
        migrations.AlterField(
            model_name='request',
            name='number_of_pages',
            field=models.IntegerField(verbose_name='Количество страниц'),
        ),
        migrations.AlterField(
            model_name='request',
            name='publishing_house',
            field=models.CharField(max_length=100, verbose_name='Издательство'),
        ),
        migrations.AlterField(
            model_name='request',
            name='the_year_of_publishing',
            field=models.IntegerField(verbose_name='Год издания'),
        ),
    ]
