# Generated by Django 3.1.7 on 2021-04-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_auto_20210403_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='formalization',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Дата'),
        ),
    ]
