# Generated by Django 3.1.7 on 2021-04-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0009_auto_20210410_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formalization',
            name='date',
            field=models.DateField(blank=True, verbose_name='Дата'),
        ),
    ]
