# Generated by Django 3.1.7 on 2021-04-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0012_auto_20210410_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formalization',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
