# Generated by Django 3.1.7 on 2021-04-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0017_auto_20210413_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='formalization',
            name='cost',
            field=models.FloatField(blank=True, default=1, verbose_name='Стоимость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formalization',
            name='total_cost',
            field=models.FloatField(default=1, verbose_name='Итоговая стоимость'),
            preserve_default=False,
        ),
    ]
